//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ME.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyAnswer
    {
        public int SurveyAnswersId { get; set; }
        public Nullable<int> SurveyId { get; set; }
        public Nullable<int> QsId { get; set; }
        public Nullable<bool> Answer { get; set; }
        public string Image { get; set; }
        public string ImagePath { get; set; }
        public string ImageExtension { get; set; }
    
        public virtual Survey Survey { get; set; }
    }
}
