//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguageDemo.Content.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RHome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguageDemo.Content.Texts.RHome", typeof(RHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details about your company or personal information.
        /// </summary>
        public static string AboutDetails {
            get {
                return ResourceManager.GetString("AboutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your company or personal information.
        /// </summary>
        public static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category Attributes.
        /// </summary>
        public static string AddCategoryAttributes {
            get {
                return ResourceManager.GetString("AddCategoryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product Attributes.
        /// </summary>
        public static string AddProductAttributes {
            get {
                return ResourceManager.GetString("AddProductAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads.
        /// </summary>
        public static string Ads {
            get {
                return ResourceManager.GetString("Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads For *.
        /// </summary>
        public static string AdsFor {
            get {
                return ResourceManager.GetString("AdsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads Type *.
        /// </summary>
        public static string AdsType {
            get {
                return ResourceManager.GetString("AdsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Values.
        /// </summary>
        public static string AttributeValues {
            get {
                return ResourceManager.GetString("AttributeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Customers.
        /// </summary>
        public static string BlockedCustomers {
            get {
                return ResourceManager.GetString("BlockedCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Vendors.
        /// </summary>
        public static string BlockedVendors {
            get {
                return ResourceManager.GetString("BlockedVendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Attributes Mappings.
        /// </summary>
        public static string CategoryAttributesMappings {
            get {
                return ResourceManager.GetString("CategoryAttributesMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Filter Mappings.
        /// </summary>
        public static string CategoryFilterMappings {
            get {
                return ResourceManager.GetString("CategoryFilterMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact information.
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has not been sent correctly. Please, try again..
        /// </summary>
        public static string ContactMessageSendNok {
            get {
                return ResourceManager.GetString("ContactMessageSendNok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent correctly. Thanks..
        /// </summary>
        public static string ContactMessageSendOk {
            get {
                return ResourceManager.GetString("ContactMessageSendOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that enables a clean separation of concerns and gives you full control over markup for enjoyable, agile development..
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Inventory.
        /// </summary>
        public static string CopyInventory {
            get {
                return ResourceManager.GetString("CopyInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        public static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Cannot Delete The End Tag..
        /// </summary>
        public static string DeleteEndTag {
            get {
                return ResourceManager.GetString("DeleteEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Deleted Successfully..
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Address.
        /// </summary>
        public static string DestinationAddress {
            get {
                return ResourceManager.GetString("DestinationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Attribute Values.
        /// </summary>
        public static string EditAttributeValues {
            get {
                return ResourceManager.GetString("EditAttributeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Filter Values.
        /// </summary>
        public static string EditFilterValues {
            get {
                return ResourceManager.GetString("EditFilterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elzamat In English.
        /// </summary>
        public static string Elzamat {
            get {
                return ResourceManager.GetString("Elzamat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Attribute Values.
        /// </summary>
        public static string EnterAttributeValues {
            get {
                return ResourceManager.GetString("EnterAttributeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Category.
        /// </summary>
        public static string EnterCategoryPlaceholder {
            get {
                return ResourceManager.GetString("EnterCategoryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Confirm Password.
        /// </summary>
        public static string EnterConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("EnterConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Description.
        /// </summary>
        public static string EnterDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("EnterDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        public static string EnterEmailPlaceholder {
            get {
                return ResourceManager.GetString("EnterEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Filter Values.
        /// </summary>
        public static string EnterFilterValues {
            get {
                return ResourceManager.GetString("EnterFilterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter First Name.
        /// </summary>
        public static string EnterFirstName {
            get {
                return ResourceManager.GetString("EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Image.
        /// </summary>
        public static string EnterImagePlaceholder {
            get {
                return ResourceManager.GetString("EnterImagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Last Name.
        /// </summary>
        public static string EnterLastName {
            get {
                return ResourceManager.GetString("EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Middle Name.
        /// </summary>
        public static string EnterMiddleName {
            get {
                return ResourceManager.GetString("EnterMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        public static string EnterNamePlaceholder {
            get {
                return ResourceManager.GetString("EnterNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Tag.
        /// </summary>
        public static string EnterNewTag {
            get {
                return ResourceManager.GetString("EnterNewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string EnterPasswordPlaceholder {
            get {
                return ResourceManager.GetString("EnterPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Price.
        /// </summary>
        public static string EnterPricePlaceholder {
            get {
                return ResourceManager.GetString("EnterPricePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Quantity.
        /// </summary>
        public static string EnterQuantityPlaceholder {
            get {
                return ResourceManager.GetString("EnterQuantityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User Name.
        /// </summary>
        public static string EnterUserNamePlaceholder {
            get {
                return ResourceManager.GetString("EnterUserNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size Cannot Exceed From 1 MB.
        /// </summary>
        public static string ErrorFileSize {
            get {
                return ResourceManager.GetString("ErrorFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        public static string Featured {
            get {
                return ResourceManager.GetString("Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Product.
        /// </summary>
        public static string FeaturedProduct {
            get {
                return ResourceManager.GetString("FeaturedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Vendor.
        /// </summary>
        public static string FeaturedVendor {
            get {
                return ResourceManager.GetString("FeaturedVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Fill The Empty Tag..
        /// </summary>
        public static string FirstFillTheEmptyTag {
            get {
                return ResourceManager.GetString("FirstFillTheEmptyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image *.
        /// </summary>
        public static string ImageRequired {
            get {
                return ResourceManager.GetString("ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Active.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert New Tags.
        /// </summary>
        public static string InsertNewTags {
            get {
                return ResourceManager.GetString("InsertNewTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Rental Vendor.
        /// </summary>
        public static string IsRentalVendor {
            get {
                return ResourceManager.GetString("IsRentalVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Seller.
        /// </summary>
        public static string IsSellerVendor {
            get {
                return ResourceManager.GetString("IsSellerVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Service Provider.
        /// </summary>
        public static string IsServiceProvider {
            get {
                return ResourceManager.GetString("IsServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Tool Vendor.
        /// </summary>
        public static string IsToolVendor {
            get {
                return ResourceManager.GetString("IsToolVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Ads.
        /// </summary>
        public static string ManageAds {
            get {
                return ResourceManager.GetString("ManageAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Attributes.
        /// </summary>
        public static string ManageAttributes {
            get {
                return ResourceManager.GetString("ManageAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Category.
        /// </summary>
        public static string ManageCategory {
            get {
                return ResourceManager.GetString("ManageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Category Attributes.
        /// </summary>
        public static string ManageCategoryAttributes {
            get {
                return ResourceManager.GetString("ManageCategoryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Category Attributes Mapping.
        /// </summary>
        public static string ManageCategoryAttributesMapping {
            get {
                return ResourceManager.GetString("ManageCategoryAttributesMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Category Filter Mapping.
        /// </summary>
        public static string ManageCategoryFilterMapping {
            get {
                return ResourceManager.GetString("ManageCategoryFilterMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Category Filters.
        /// </summary>
        public static string ManageCategoryFilters {
            get {
                return ResourceManager.GetString("ManageCategoryFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Customers.
        /// </summary>
        public static string ManageCustomers {
            get {
                return ResourceManager.GetString("ManageCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Customers List.
        /// </summary>
        public static string ManageCustomersList {
            get {
                return ResourceManager.GetString("ManageCustomersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Delivery.
        /// </summary>
        public static string ManageDelivery {
            get {
                return ResourceManager.GetString("ManageDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Filters.
        /// </summary>
        public static string ManageFilters {
            get {
                return ResourceManager.GetString("ManageFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Messages.
        /// </summary>
        public static string ManageMessages {
            get {
                return ResourceManager.GetString("ManageMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Orders.
        /// </summary>
        public static string ManageOrders {
            get {
                return ResourceManager.GetString("ManageOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Portals.
        /// </summary>
        public static string ManagePortals {
            get {
                return ResourceManager.GetString("ManagePortals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Product Attributes.
        /// </summary>
        public static string ManageProductAttributes {
            get {
                return ResourceManager.GetString("ManageProductAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Product Attributes Mapping.
        /// </summary>
        public static string ManageProductAttributesMapping {
            get {
                return ResourceManager.GetString("ManageProductAttributesMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Product Filters.
        /// </summary>
        public static string ManageProductFilters {
            get {
                return ResourceManager.GetString("ManageProductFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Product Filters Mapping.
        /// </summary>
        public static string ManageProductFiltersMapping {
            get {
                return ResourceManager.GetString("ManageProductFiltersMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Products.
        /// </summary>
        public static string ManageProducts {
            get {
                return ResourceManager.GetString("ManageProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Vendors.
        /// </summary>
        public static string ManageVendors {
            get {
                return ResourceManager.GetString("ManageVendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Vendors List.
        /// </summary>
        public static string ManageVendorsList {
            get {
                return ResourceManager.GetString("ManageVendorsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name*.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNo.
        /// </summary>
        public static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Category.
        /// </summary>
        public static string ParentCategory {
            get {
                return ResourceManager.GetString("ParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        public static string Portal {
            get {
                return ResourceManager.GetString("Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Portals.
        /// </summary>
        public static string PortalHeading {
            get {
                return ResourceManager.GetString("PortalHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Management.
        /// </summary>
        public static string PortalManagement {
            get {
                return ResourceManager.GetString("PortalManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Name.
        /// </summary>
        public static string PortalName {
            get {
                return ResourceManager.GetString("PortalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Attributes Mappings.
        /// </summary>
        public static string ProductAttributesMappings {
            get {
                return ResourceManager.GetString("ProductAttributesMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Filters Mappings.
        /// </summary>
        public static string ProductFiltersMappings {
            get {
                return ResourceManager.GetString("ProductFiltersMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name*.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductNameNotRequired {
            get {
                return ResourceManager.GetString("ProductNameNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Products Tree.
        /// </summary>
        public static string ProductsTree {
            get {
                return ResourceManager.GetString("ProductsTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries.
        /// </summary>
        public static string Queries {
            get {
                return ResourceManager.GetString("Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Vendor.
        /// </summary>
        public static string RentalVendor {
            get {
                return ResourceManager.GetString("RentalVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Ads For --.
        /// </summary>
        public static string SelectAdsPlacholder {
            get {
                return ResourceManager.GetString("SelectAdsPlacholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Ads Type --.
        /// </summary>
        public static string SelectAdsTypePlacholder {
            get {
                return ResourceManager.GetString("SelectAdsTypePlacholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Attribute --.
        /// </summary>
        public static string SelectAttributePlacholder {
            get {
                return ResourceManager.GetString("SelectAttributePlacholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Attributes*.
        /// </summary>
        public static string SelectAttributes {
            get {
                return ResourceManager.GetString("SelectAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category*.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Category -- .
        /// </summary>
        public static string SelectCategoryPlacholder {
            get {
                return ResourceManager.GetString("SelectCategoryPlacholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Customer.
        /// </summary>
        public static string SelectCustomer {
            get {
                return ResourceManager.GetString("SelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Customer --.
        /// </summary>
        public static string SelectCustomerPlacholder {
            get {
                return ResourceManager.GetString("SelectCustomerPlacholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Filters --.
        /// </summary>
        public static string SelectFilterPlaceholder {
            get {
                return ResourceManager.GetString("SelectFilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Filters*.
        /// </summary>
        public static string SelectFilters {
            get {
                return ResourceManager.GetString("SelectFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Portal.
        /// </summary>
        public static string SelectPortal {
            get {
                return ResourceManager.GetString("SelectPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Portal --.
        /// </summary>
        public static string SelectPortalPlaceholder {
            get {
                return ResourceManager.GetString("SelectPortalPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectPortal*.
        /// </summary>
        public static string SelectPortalRequired {
            get {
                return ResourceManager.GetString("SelectPortalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Product*.
        /// </summary>
        public static string SelectProduct {
            get {
                return ResourceManager.GetString("SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Product --.
        /// </summary>
        public static string SelectProductPlacholder {
            get {
                return ResourceManager.GetString("SelectProductPlacholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status.
        /// </summary>
        public static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Status --.
        /// </summary>
        public static string SelectStatusPlaceholder {
            get {
                return ResourceManager.GetString("SelectStatusPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tags.
        /// </summary>
        public static string SelectTags {
            get {
                return ResourceManager.GetString("SelectTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Tags --.
        /// </summary>
        public static string SelectTagsPlaceholder {
            get {
                return ResourceManager.GetString("SelectTagsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Vendor.
        /// </summary>
        public static string SelectVendor {
            get {
                return ResourceManager.GetString("SelectVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Vendor --.
        /// </summary>
        public static string SelectVendorPlacholder {
            get {
                return ResourceManager.GetString("SelectVendorPlacholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Vendor.
        /// </summary>
        public static string SellerVendor {
            get {
                return ResourceManager.GetString("SellerVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sr#.
        /// </summary>
        public static string SerialNo {
            get {
                return ResourceManager.GetString("SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider.
        /// </summary>
        public static string ServiceProvider {
            get {
                return ResourceManager.GetString("ServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category Name.
        /// </summary>
        public static string SubCategoryName {
            get {
                return ResourceManager.GetString("SubCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET is a free web framework for building great Multi-Language MVC Web sites and Web applications using HTML, CSS and JavaScript..
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Saved Successfully..
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR FIRST MULTI-LANGUAGE MVC APPLICATION.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Vendor.
        /// </summary>
        public static string ToolVendor {
            get {
                return ResourceManager.GetString("ToolVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors Name.
        /// </summary>
        public static string VendorName {
            get {
                return ResourceManager.GetString("VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        public static string Vendors {
            get {
                return ResourceManager.GetString("Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Inventory.
        /// </summary>
        public static string YourInventory {
            get {
                return ResourceManager.GetString("YourInventory", resourceCulture);
            }
        }
    }
}
